version: '3.7'
services:
  db:
    image: postgres:13.4@sha256:97e5e91582e89514277912d4b7c95bceabdede3482e32395bcb40099abd9c506
    env_file:
      - ./.env.example
    environment:
      POSTGRES_DB: ${SQL_DATABASE:-audit}
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - ${SQL_PORT:-5432}
    restart: on-failure
  web:
    build: 
      context: ./
    image: mobile_audit
    env_file:
      - ./.env.example
    entrypoint: [ '/web_entrypoint.sh' ]
    volumes:
      - app-data:/app
    expose:
      - "8000"
    depends_on:
      - db
    restart: on-failure
  nginx:
    image: nginx:1.21.3@sha256:853b221d3341add7aaadf5f81dd088ea943ab9c918766e295321294b035f3f3e
    ports:
      - "8888:8888"
    volumes:
      - app-data:/app
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
      - web
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.8.14-management@sha256:c7e1e3c34f1a6a5c089723763f04dc4c483d12f2fabb2fe48faee6f3d3998c69
    env_file:
      - ./.env.example
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - rabbitmq-logs-data:/var/log/rabbitmq/
    expose:
      - "5672"
    depends_on:
      - web
    restart: on-failure
  worker:
    image: mobile_audit
    env_file:
      - ./.env.example
    entrypoint: [ '/worker_entrypoint.sh' ]
    volumes:
      - app-data:/app
    links:
      - rabbitmq
      - web
    depends_on:
      - rabbitmq
    restart: on-failure
volumes:
  db-data:
  app-data:
  rabbitmq-logs-data:
